# Generated by Django 5.1.6 on 2025-06-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaoRendimento',
            fields=[
                ('escalao_rendimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('percentagem_mensalidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentagem_caf_classico_almoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentagem_caf_classico_sem_almoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentagem_caf_ext_almoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentagem_caf_ext_sem_almoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentagem_caf_conciliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'escalao_rendimento',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='escalao',
            field=models.ForeignKey(blank=True, db_column='escalao_rendimento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_hub.escalaorendimento'),
        ),
    ]
