# Generated by Django 5.1.6 on 2025-06-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_escalaorendimento_aluno_escalao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaorendimento',
            name='rmmg_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='escalaorendimento',
            name='rmmg_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
