# Generated by Django 5.1.6 on 2025-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0007_alter_cuidadoespecial_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaoRendimento',
            fields=[
                ('escal_rend_id', models.AutoField(primary_key=True, serialize=False)),
                ('rend_per_capita', models.IntegerField()),
                ('escalao', models.CharField(max_length=255)),
                ('comparticipacao_da_familia', models.IntegerField()),
            ],
        ),
    ]
